trigger: none


pool:
  vmImage: 'Ubuntu-16.04'

resources:
  repositories:

    - repository: tests
      type: github
      name: michalO01/temp
      #ref: refs/tags/0.3.2
      #ref: refs/heads/feature/parametrization
      #ref: refs/tags/0.4.1
      endpoint: crux

variables:
  imageName: 'appxx-img'
  dockerfilePath: 'bulletin-board-app/Dockerfile'
  dockerRegistryServiceConnection: boostRegistryServiceConnection
  armServiceConnectionBoost: boost
  appName: appxx
  container: appxx.azurecr.io/appxx-img:latest

stages:
- stage: Build
  displayName: Test, Build and Push docker image
  jobs:
  - job: Build
    displayName: Test, Build, Push
    steps:
    - bash: | #this can be run inside docker image
        echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee -a /etc/apt/sources.list.d/google.list
        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        # Add Node's apt-key
        curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
        # Install NodeJS and Google Chrome
        sudo apt-get update
        sudo apt-get install -y nodejs google-chrome-stable
        ls
        cd bulletin-board-app
        sudo npm  install
        export CHROME_PATH=$(which google-chrome-stable)
        export LHCI_BUILD_CONTEXT__EXTERNAL_BUILD_URL="$BUILD_URL"
        export LHCI_BUILD_CONTEXT__CURRENT_BRANCH=$(Build.SourceBranchName) #otherwise upload will fail
        sudo npm install -g @lhci/cli@0.6.x
        lhci autorun
      displayName: Lighthouse tests


